
export const socials = [
  { key: 1,
    name: 'twitter',
    imgurl: '/footerSocials/twitter.svg',
    socialurl: 'https://twitter.com/',
  },
  { key: 2,
    name: 'linkedin',
    imgurl: '/footerSocials/linkedin.svg',
    socialurl: 'https://www.linkedin.com/company/',
  },
  { key: 3,
    name: 'instagram',
    imgurl: '/footerSocials/instagram.svg',
    socialurl: 'https://www.instagram.com/',
  },
  // { key: 4,
  //   name: 'facebook',
  //   imgurl: '/footerSocials/facebook.svg',
  //   socialurl: 'https://www.facebook.com/',
  // },
  { key: 5,
    name: 'youtube',
    imgurl: '/footerSocials/youtube.svg',
    socialurl: 'https://www.youtube.com/',
  },
  { key: 6,
    name: 'phonecall',
    imgurl: '/footerSocials/phonecall.svg',
    socialurl: 'tel:9860026957',
  },
];

